import { CategoryName } from 'types/categories';

const INFO_CATEGORY_TAGS: { [key: string]: CategoryName } = {
  TRAVEL__INFORMATION__PUBLIC: 'TRAVEL',
  TRANSPORT__INFORMATION__PUBLIC: 'TRANSPORT',
  CAREER__INFORMATION__PUBLIC: 'CAREER',
  SOCIAL_INTERESTS__INFORMATION__PUBLIC: 'SOCIAL_INTERESTS',
  HOME__INFORMATION__PUBLIC: 'HOME',
  GARDEN__INFORMATION__PUBLIC: 'GARDEN',
  FOOD__INFORMATION__PUBLIC: 'FOOD',
  LAUNDRY__INFORMATION__PUBLIC: 'LAUNDRY'
};

export default INFO_CATEGORY_TAGS;
