# Generated by Django 4.0.4 on 2023-09-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_calendars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icalintegration',
            name='ical_text',
            field=models.TextField(default=''),
        ),
    ]
