# Generated by Django 4.0.4 on 2023-09-27 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_linklistsetupcompletion'),
        ('external_calendars', '0002_icalintegration_ical_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icalintegration',
            name='ical_text',
        ),
        migrations.CreateModel(
            name='ICalEvent',
            fields=[
                ('fixedtask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.fixedtask')),
                ('ical_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ical_events', to='external_calendars.icalintegration')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.fixedtask', models.Model),
        ),
    ]
