# Generated by Django 4.0.4 on 2023-09-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_calendars', '0003_remove_icalintegration_ical_text_icalevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='icalintegration',
            name='ical_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
