# Generated by Django 4.0.4 on 2023-09-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_calendars', '0004_icalintegration_ical_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='icalintegration',
            name='ical_type',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('GOOGLE', 'Google'), ('ICLOUD', 'ICloud'), ('OUTLOOK', 'Outlook')], default='', max_length=63),
        ),
    ]
