# Generated by Django 4.0.4 on 2023-09-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_calendars', '0005_icalintegration_ical_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='icalintegration',
            name='share_type',
            field=models.CharField(choices=[('OFF', 'Off'), ('BUSY', 'Busy'), ('FULL', 'Full')], default='OFF', max_length=63),
        ),
        migrations.AlterField(
            model_name='icalintegration',
            name='ical_type',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('GOOGLE', 'Google'), ('ICLOUD', 'ICloud'), ('OUTLOOK', 'Outlook')], default='UNKNOWN', max_length=63),
        ),
    ]
