const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
const SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN';
const SET_USERNAME = 'SET_USERNAME';

export default {
  SET_ACCESS_TOKEN,
  SET_REFRESH_TOKEN,
  SET_USERNAME
};

export { SET_ACCESS_TOKEN, SET_REFRESH_TOKEN, SET_USERNAME };
