const SET_ALL_TASKS = 'SET_ALL_TASKS';
const SET_TASK_COMPLETION = 'SET_TASK_COMPLETION';
const SET_TASK_BY_ID = 'SET_TASK_BY_ID';

export default {
  SET_ALL_TASKS,
  SET_TASK_COMPLETION,
  SET_TASK_BY_ID
};

export { SET_ALL_TASKS, SET_TASK_COMPLETION, SET_TASK_BY_ID };
