# Generated by Django 4.0.4 on 2023-09-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tagsetupcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskactioncompletionform',
            name='complete',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='taskcompletionform',
            name='complete',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
