# Generated by Django 4.0.4 on 2023-09-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='read',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
