# Generated by Django 4.0.4 on 2023-09-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alert_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionalert',
            name='read',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
