# Generated by Django 4.0.4 on 2023-09-28 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_actionalert_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastActivityView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_activity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
