# Generated by Django 4.0.4 on 2023-10-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lastactivityview'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcompletionform',
            name='partial',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
