# Generated by Django 4.0.4 on 2023-10-11 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_taskcompletionform_partial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestListInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('accepted', models.BooleanField(blank=True, default=False)),
                ('rejected', models.BooleanField(blank=True, default=False)),
                ('maybe', models.BooleanField(blank=True, default=False)),
                ('entity', models.ForeignKey(help_text='Should be an AutoSubentity entity', on_delete=django.db.models.deletion.CASCADE, related_name='guest_list_invites', to='core.entity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_list_invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
