# Generated by Django 4.0.4 on 2023-10-11 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_guestlistinvite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='entity_ptr',
        ),
        migrations.RemoveField(
            model_name='hotelorrental',
            name='entity_ptr',
        ),
        migrations.RemoveField(
            model_name='rentalcar',
            name='entity_ptr',
        ),
        migrations.RemoveField(
            model_name='staywithfriend',
            name='entity_ptr',
        ),
        migrations.RemoveField(
            model_name='taxiortransfer',
            name='entity_ptr',
        ),
        migrations.RemoveField(
            model_name='trainbusferry',
            name='entity_ptr',
        ),
        migrations.RemoveField(
            model_name='tripactivity',
            name='entity_ptr',
        ),
        migrations.AlterField(
            model_name='entity',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DriveTime',
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
        migrations.DeleteModel(
            name='HotelOrRental',
        ),
        migrations.DeleteModel(
            name='RentalCar',
        ),
        migrations.DeleteModel(
            name='StayWithFriend',
        ),
        migrations.DeleteModel(
            name='TaxiOrTransfer',
        ),
        migrations.DeleteModel(
            name='TrainBusFerry',
        ),
        migrations.DeleteModel(
            name='TripActivity',
        ),
    ]
