# Generated by Django 4.0.4 on 2023-10-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_flight_entity_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestlistinvite',
            name='sent',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
