# Generated by Django 4.0.4 on 2023-10-12 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_guestlistinvite_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlistinvite',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='guestlistinvite',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_list_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='guestlistinvite',
            unique_together={('phone_number', 'entity'), ('user', 'entity'), ('email', 'entity')},
        ),
    ]
