# Generated by Django 4.0.4 on 2023-10-12 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_guestlistinvite_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlistinvite',
            name='entity',
            field=models.ForeignKey(blank=True, default=None, help_text='Should be an AutoSubentity entity', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_list_invites', to='core.entity'),
        ),
    ]
