# Generated by Django 4.0.4 on 2023-10-12 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_guestlistinvite_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlistinvite',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guestlistinvite',
            name='entity',
            field=models.ForeignKey(default=0, help_text='Should be an AutoSubentity entity', on_delete=django.db.models.deletion.CASCADE, related_name='guest_list_invites', to='core.entity'),
            preserve_default=False,
        ),
    ]
