# Generated by Django 4.0.4 on 2023-10-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_guestlistinvite_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestlistinvite',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
