# Generated by Django 4.0.4 on 2023-10-16 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_professionalentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalEntityCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professionalcategory')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professionalentity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'entity')},
            },
        ),
    ]
