# Generated by Django 4.0.4 on 2023-10-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_professionalentitycategorymapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalentity',
            name='professional_category',
        ),
    ]
