# Generated by Django 4.0.4 on 2023-10-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_professionalentity_professional_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexibletaskcompletionform',
            name='taskcompletionform_ptr',
        ),
        migrations.AlterModelOptions(
            name='taskcompletionform',
            options={},
        ),
        migrations.RemoveField(
            model_name='taskcompletionform',
            name='polymorphic_ctype',
        ),
        migrations.DeleteModel(
            name='FixedTaskCompletionForm',
        ),
        migrations.DeleteModel(
            name='FlexibleTaskCompletionForm',
        ),
    ]
