# Generated by Django 4.0.4 on 2023-11-09 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_flexibletaskcompletionform_taskcompletionform_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBirthdayTask',
            fields=[
                ('fixedtask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.fixedtask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.fixedtask',),
        ),
    ]
