# Generated by Django 4.0.4 on 2025-03-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_userbirthdaytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexibletask',
            name='urgency',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(blank=True, choices=[('TASK', 'Task'), ('APPOINTMENT', 'Appointment'), ('DUE_DATE', 'Due Date'), ('FLIGHT', 'Flight'), ('TRAIN', 'Train'), ('RENTAL_CAR', 'Rental Car'), ('TAXI', 'Taxi'), ('DRIVE_TIME', 'Drive Time'), ('HOTEL', 'Hotel'), ('STAY_WITH_FRIEND', 'Stay With Friend'), ('ACTIVITY', 'Activity'), ('FOOD_ACTIVITY', 'Food'), ('OTHER_ACTIVITY', 'Other Activity'), ('ANNIVERSARY', 'Anniversary'), ('BIRTHDAY', 'Birthday'), ('USER_BIRTHDAY', 'User Birthday'), ('HOLIDAY', 'Holiday'), ('ICAL_EVENT', 'ICal Event')], default='TASK', max_length=20),
        ),
    ]
