# Generated by Django 4.0.4 on 2025-04-05 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_timeblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblock',
            name='members',
            field=models.ManyToManyField(related_name='timeblocks', to=settings.AUTH_USER_MODEL),
        ),
    ]
