const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
const SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN';
const SET_USERNAME = 'SET_USERNAME';
const LOGOUT = 'LOGOUT';

export default {
  SET_ACCESS_TOKEN,
  SET_REFRESH_TOKEN,
  SET_USERNAME,
  LOGOUT
};

export { SET_ACCESS_TOKEN, SET_REFRESH_TOKEN, SET_USERNAME, LOGOUT };
